name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *'  # Sync every 3 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sync Fork Action
      uses: XueMoMo/Sync-Fork-action@v1.0.6

